import type { Metadata } from "next";
import "./globals.css";
import React from "react";
import {ReduxProvider} from "@/app/Provider";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className="antialiased">
        <ReduxProvider>
            {children}
        </ReduxProvider>
        </body>
        </html>
    );
}
